<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- WinUI / Windows App SDK -->
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
  </ItemGroup>

  <ItemGroup>
    <!-- Testing -->
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
    <PackageVersion Include="coverlet.mtp" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Versioning and source linking -->
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.400" />
  </ItemGroup>

</Project>
